stages:
  - build
  - test
  - packaging

# DinD service is required for Testcontainers
services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: ["--tls=false"]

variables:
  # Instruct Testcontainers to use the daemon of DinD, use port 2375 for non-tls connections.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

build_job:
  stage: build
  image: gradle:7.3.3-jdk17-alpine
  script:
    - chmod +x ./gradlew  # Ensure the gradlew script is executable
    - ./gradlew clean assemble

test_job:
  stage: test
  image: gradle:7.3.3-jdk17-alpine
  script:
    - chmod +x ./gradlew  # Ensure the gradlew script is executable
    - ./gradlew test --info --stacktrace  # Add more details to the test output
  artifacts:
    when: always  # Keep test reports regardless of success or failure
    reports:
      junit: build/test-results/test/*.xml  # Publish JUnit test reports
    paths:
      - build/reports/tests/test  # Include HTML test reports for additional visibility
    expire_in: 1 day


packaging_job:
  stage: packaging
  image: gradle:7.3.3-jdk17-alpine
  script:
    - chmod +x ./gradlew  # Ensure the gradlew script is executable
    - ./gradlew clean assemble  # Build the JAR
    - mkdir -p packaging
    - cp build/libs/*.jar packaging/  # Copy the JAR to a packaging directory
  artifacts:
    paths:
      - packaging/*.jar  # Save the JAR files for further use
    expire_in: 1 day
