services:
  db_postgresql:
    image: postgres:15.8-alpine
    environment:
      POSTGRES_DB: 'poker_db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes:
      - ./kdg/postgres/data:/var/lib/postgresql/data

  kdg_idp_postgres:
    image: postgres:15.8-alpine
    volumes:
      - ./kdg/idp/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - kc

  kdg_idp_keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_DB=postgres
      - KC_DB_URL_HOST=kdg_idp_postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - kdg_idp_postgres
    networks:
      - kc

  rabbitmq:
    image: rabbitmq:3.12.4-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management console
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
    networks:
      - backend

networks:
  kc:
    name: kc-network
    driver: bridge
  backend:
    name: back-network
    driver: bridge
